### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by dariusf**
Hi, I was trying to update the examples to better understand this library, and had some questions about the one for well-scoped lambda terms.

I got stuck at line 98, where we want to build a FuelGen.t (a generator of new lambda terms) which is dependent on a Gen.t (a generator of variable names). I was thinking the solution would be to lift a Gen.t to a FuelGen.t, but then there is no monad instance for FuelGen.t.

To begin with, is such an instance possible/a good idea? I'm not sure how a join operation should distribute the fuel. I also saw `fueled` used to be defined as `(int -> 'a option) gen`, which would allow this to work, but what are the tradeoffs of that definition?

Any other tips would be welcome!

(To get everything compiling, I commented out the parts which depend on PArray, which is absent. Noticed there was a PArray module in history and I can restore it when done, as well as clean things up in general.)

### CODE REVIEW

**Comment by gasche** [comment]
Hi @dariusf,

Thanks for catching this! The API is very different in master and I hadn't tried updating the example code. I should have, because as you point out this highlights pain points with the new API.

I pushed a few commits to master that fix example.ml at last. We would still need to go over the generator.mli in-documentation examples to see if they need to be adapted.
(I apologize for pushing directly instead of helping you solve the problem; your issue let me realized that the repo was in a sorry state and I focused on fixing this, not realizing that it was actually a PR with a part of the solution... Well let's hope it was at least an excellent exercise for you.)

(I also reinstated PArray. I'm not sure why it was not committed, probably a silly `git add` mistake at the time I changed the API. Apologies for this as well.)

As you realized, it is unclear we want to implement `bind`, in fact `join : 'a FuelGen.t FuelGen.t -> 'a FuelGen.t`, because there is no canonical way to split the fuel between the two layers. (One would first think of using the uniform 2-way split, but this would behave very poorly with sequences of repeated binds.)
The solution is to implement "lesser" join operators which do *not* require splitting the fuel. For this example we need `join_in_gen : 'a FuelGen.t Gen.t -> 'a FuelGen.t`, which I implemented as I converted the example.

(I wasn't sure how to name this operator. Note that in general there are two join operations, one where the FuelGen is "inside" the Gen and the other when it is "outside". In practice I think we need the inside join more, so i only added it, with `_in_` as a reminder in the name.)

This difficulty was in fact created by a change I made when I updated the API, to move the definition of `'a FuelGen.t` from the previous `(int -> 'a option) Gen.t` to the new `int -> 'a BacktrackGen.t`. The previous API was weirder as a type definition, but it allowed to use the bind operator of Gen.t directly, hiding this difficulty.
Note: with the previous API, we always had `type 'a Gen.t = Random.State.t -> 'a`, so in fact the two definitions were equivalent (`int -> Random.State.t -> 'a option` vs. `Random.State.t -> int -> 'a option`). With the new, parametrized API, `'a Gen.t` is not necessarily an arrow type and the two choices are not isomorphic. I think that `int -> 'a Prob.t` is a better choice than `(int -> 'a) Prob.t`.

**Comment by dariusf** [comment]
Thanks for the fixes and explanation! That's a very neat solution. I updated the docs in the mli, just to finish this.

With the new function, I don't have any more issues with the API, it's nice and intuitive. A small thing which that may trip people up is keeping track of which `let+` operator is in scope when `open`ing FuelGen (in the random_tree example), as the type error that appears doesn't point to that as the problem.

**Comment by gasche** [comment]
Thanks for the fixes!

We could have different binding operators for the different monads, but we are stuck with infix symbols and it is not clear what to use. I thought of `let*?` for BacktrackGen, but I don't know how to distinguish Gen vs. FuelGen in a non-obscure way. (FuelGen has no bind but ideally we could use the same convention for the maps, `let+`, `let+?` and...?)

(There are talks of allowing `let.foo` in the OCaml lexer which would of course be great here, but mere talks for now.)

**Comment by dariusf** [comment]
Maybe `let+*`? `*` being evocative of finite repetition. 😆 

Since there is no `let**`, we won't have two `*`s with different meanings.

**Pull request merged**
